#MODEL:
num_classes: 81
ignore_value: 255

#OPTIM:
epochs: 100
lr: 0.05
momentum: 0.9
weight_decay: 0.0001
bn_weight_decay: False
bn_precise_stats: False
bn_precise_num_samples: 600
lr_scheduler: poly
poly_power: 0.9
warmup_iters: 10
warmup_factor: 0.01

#TRAIN:
mixed_precision: True
run: 1
RNG_seed: 0
loss_type: cross_entropy
exclude_classes: []

#dataset
dataset_name: coco
batch_size: 8
train_min_size: 256
train_max_size: 1024
train_crop_size: [1024,1024]
val_input_size: [1024,1024]
val_label_size: [1024,1024]
aug_mode: baseline
num_workers: 4
class_uniform_pct: 0
train_split: train
val_split: val
max_eval: 10000
eval_print_every: 1000
train_print_every: 400

#checkpoint
eval_every_k_epochs: 50
eval_last_k_epochs: 1
save_dir: /scratch/models_coco/
dataset_dir : /scratch/coco
model_repo_path : /scratch/
model_path : /scratch/models/
